### REST Client  
@resourcegroupname=rg-dicom-rest
@workspacename=ws11
@dicomservicename=dicom11
@location=southcentralus
@subscriptionid=cc148bf2-42fb-4913-a3fb-2f284a69eb89
@tenantid=72f988bf-86f1-41af-91ab-2d7cd011db47
@clientid=b4b81ba7-7d13-4d10-ae2c-c097c5dd79c9
@clientsecret=1~uOXvbD-9cXsQCc~7N3~Djcd1l77uu5d7
@resource=https://management.azure.com/
@authorityurl=https://login.microsoftonline.com
@apiversion=2020-11-01-preview
#@apiversion=2021-03-30-preview

### Get an access token
# @name getToken
POST https://login.microsoftonline.com/{{tenantid}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&resource={{resource}}
&client_id={{clientid}}
&client_secret={{clientsecret}}

### Capture access token from getToken request
@token = {{getToken.response.body.access_token}}

### create resource group
PUT https://management.azure.com/subscriptions/{{subscriptionid}}/resourcegroups/{{resourcegroupname}}?api-version=2021-04-01
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "location": "{{location}}"
}

### create workspace
Put https://management.azure.com/subscriptions/{{subscriptionid}}/resourceGroups/{{resourcegroupname}}/providers/Microsoft.HealthcareApis/workspaces/{{workspacename}}?api-version={{apiversion}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "{{workspacename}}",
    "type": "Microsoft.HealthcareApis/workspaces",
    "location": "{{location}}",
    "properties": {
    }
}

### create DICOM instance
PUT  https://management.azure.com/subscriptions/{{subscriptionid}}/resourceGroups/{{resourcegroupname}}/providers/Microsoft.HealthcareApis/workspaces/{{workspacename}}/dicomservices/{{dicomservicename}}?api-version={{apiversion}}  
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": "{{dicomservicename}}",
  "type": "Microsoft.HealthcareApis/workspaces/dicomservices",
  "location": "{{location}}",
  "properties": {
    "accessPolicies": []    }
  }
}

