### REST Client - an alternative to Postman
@dicomresource=https://ws1-dicom11.dicom.azurehealthcareapis.com
@tenantid=72f988bf-86f1-41af-91ab-2d7cd011db47
@clientid=b4b81ba7-7d13-4d10-ae2c-c097c5dd79c9
@clientsecret=1~uOXvbD-9cXsQCc~7N3~Djcd1l77uu5d7
@aadresource=https://dicom.healthcareapis.azure.com/
@studyid=1.2.826.0.1.3680043.8.498.13230779778012324449356534479549187420
@seriesid1=1.2.826.0.1.3680043.8.498.45787841905473114233124723359129632652
@seriesid2=1.2.826.0.1.3680043.8.498.77033797676425927098669402985243398207
@instanceid1=1.2.826.0.1.3680043.8.498.12714725698140337137334606354172323212
@instanceid2=1.2.826.0.1.3680043.8.498.47359123102728459884412887463296905395
@instanceid3=1.2.826.0.1.3680043.8.498.13273713909719068980354078852867170114
@dicomaadresource=https://dicom.healthcareapis.azure.com/

###get token
#token=$(az account get-access-token --resource=https://dicom.healthcareapis.azure.com/ --query accessToken --output tsv) 
# @name getToken 
POST https://login.microsoftonline.com/{{tenantid}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&resource={{dicomaadresource}}
&client_id={{clientid}}
&client_secret={{clientsecret}}

### Capture access token from getToken request
@token = {{getToken.response.body.access_token}}

### post
#https://github.com/microsoft/dicom-server/blob/main/docs/resources/conformance-statement.md#store-stow-rs
Post {{dicomresource}}/studies/1.2.826.0.1.3680043.8.498.13230779778012324449356534479549187420
Content-Type: multipart/related; boundary=MyBoundary
Accept: application/dicom+json
Authorization: Bearer {{token}}

--MyBoundary
Content-Disposition: form-data; 
Content-Type: application/dicom

< C:\temp\dicomsampleimages\DICOM Sample\red-triangle.dcm

--MyBoundary--

### post
Post {{dicomresource}}/studies
Content-Type: multipart/related; boundary=MyBoundary
Accept: application/dicom+json
Authorization: Bearer {{token}}

--MyBoundary
Content-Disposition: form-data; 
Content-Type: application/dicom

< C:\temp\dicomsampleimages\DICOM Sample\image-000001.dcm

--MyBoundary--

### get
Get {{dicomresource}}/studies
Content-Type: multipart/related; transfer-syntax=*
Accept: application/dicom+json
Authorization: Bearer {{token}}

###retrieve one or more frames from one instance
Get {{dicomresource}}/studies/{{studyid}}/series/{{seriesid1}}/instances/{{instanceid1}}/frames/1
Accept: multipart/related; type="application/octet-stream"; 
Authorization: Bearer {{token}}

### get (no aad token)
Get https://bxdicom1.azurewebsites.net/studies/{{studyid}}/series/{{seriesid2}}/instances/{{instanceid3}}/frames/1
Accept: multipart/related; type="application/octet-stream"; transfer-syntax=1.2.840.10008.1.2.1

###change feed
Get {{dicomresource}}/changefeed?includemetadata=false
Authorization: Bearer {{token}}

### change feed (no token required)
Get https://bxdicom1.azurewebsites.net/changefeed?includemetadata=false

