### REST Client - an alternative to Postman
@fhiraudience=https://ws1-fhirdata.fhir.azurehealthcareapis.com
@clientid=b4b81ba7-7d13-4d10-ae2c-c097c5dd79c9
@clientsecret=1~uOXvbD-9cXsQCc~7N3~Djcd1l77uu5d7
@tenantid=72f988bf-86f1-41af-91ab-2d7cd011db47

### Get metadata
Get audience}}/metadata

### Get access token 
# @name getToken 
POST https://login.microsoftonline.com/{{tenantid}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&resource={{fhiraudience}}
&client_id={{clientid}}
&client_secret={{clientsecret}}

### Capture access token from getToken request
@token = {{getToken.response.body.access_token}}

### Get Patient Data
Get audience}}/Patient
Authorization: Bearer {{token}}

### Get Patient count
Get {{fhiraudience}}/Patient?_summary=count
Authorization: Bearer {{token}}

### Get Encounter count
Get {{fhiraudience}}/Encounter?_summary=count
Authorization: Bearer {{token}}

### export
Get {{fhiraudience}}/$export?_container=export
Authorization: Bearer {{token}}
Accept: application/fhir+json
Prefer: respond-async
//https://himss21-fhir21.fhir.azurehealthcareapis.com/_operations/export/7afe307f-6b61-41bf-a454-4d732caf769f

### get export status
Get audience}}/_operations/export/7afe307f-6b61-41bf-a454-4d732caf769f
Authorization: Bearer {{token}}


### Get Patient Data
Post {{fhiraudience}}/Patient
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "resourceType": "Patient",
    "id": "845e2bf7-6d8e-0cb3-a4f0-3e2a03526c3f",
    "meta": {
        "versionId": "6",
        "lastUpdated": "2021-02-06T03:05:45.825+00:00"
    },
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: master-branch-latest-2-gfd2217b\n .   Person seed: -4589683661576670669  Population seed: 98052</div>"
    },
    "extension": [
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Deanna833 Berge125"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
                "city": "Boston",
                "state": "Massachusetts",
                "country": "US"
            }
        },
        {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 0.16945176064877046
        },
        {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 49.83054823935123
        }
    ],
    "identifier": [
        {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "845e2bf7-6d8e-0cb3-a4f0-3e2a03526c3f"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR",
                        "display": "Medical Record Number"
                    }
                ],
                "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "845e2bf7-6d8e-0cb3-a4f0-3e2a03526c3f"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "SS",
                        "display": "Social Security Number"
                    }
                ],
                "text": "Social Security Number"
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-40-7444"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "DL",
                        "display": "Driver's License"
                    }
                ],
                "text": "Driver's License"
            },
            "system": "urn:oid:2.16.840.1.113883.4.3.25",
            "value": "S99928395"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "PPN",
                        "display": "Passport Number"
                    }
                ],
                "text": "Passport Number"
            },
            "system": "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
            "value": "X40358018X"
        }
    ],
    "name": [
        {
            "use": "official",
            "family": "Batz141",
            "given": [
                "Aaron697"
            ],
            "prefix": [
                "Mr."
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "555-286-5250",
            "use": "home"
        }
    ],
    "gender": "male",
    "birthDate": "1969-11-22",
    "address": [
        {
            "extension": [
                {
                    "extension": [
                        {
                            "url": "latitude",
                            "valueDecimal": 42.341566160908336
                        },
                        {
                            "url": "longitude",
                            "valueDecimal": -71.54441962893634
                        }
                    ],
                    "url": "http://hl7.org/fhir/StructureDefinition/geolocation"
                }
            ],
            "line": [
                "769 Dach Mews"
            ],
            "city": "Marlborough",
            "state": "Massachusetts",
            "postalCode": "01752",
            "country": "US"
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                "code": "S",
                "display": "S"
            }
        ],
        "text": "S"
    },
    "multipleBirthBoolean": false,
    "communication": [
        {
            "language": {
                "coding": [
                    {
                        "system": "urn:ietf:bcp:47",
                        "code": "en-US",
                        "display": "English"
                    }
                ],
                "text": "English"
            }
        }
    ]
}